name: qwen3
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - icu=75.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libcurl=8.16.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.86.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - nspr=4.37
  - nss=3.117
  - openjpeg=2.5.4
  - openssl=3.5.4
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - poppler=25.07.0
  - poppler-data=0.4.12
  - pthread-stubs=0.4
  - python=3.11.13
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - autoawq==0.2.9
      - av==15.1.0
      - bert-score==0.3.13
      - brotli==1.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.1.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - decord==0.6.0
      - dill==0.4.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - evaluate==0.4.6
      - executing==2.2.1
      - ffmpeg-python==0.2.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.1.1
      - future==1.0.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - idna==3.10
      - imagehash==4.3.2
      - imageio==2.37.0
      - iopath==0.1.10
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mutagen==1.47.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.2
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pdf2image==1.17.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - poppler-utils==0.1.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pycryptodomex==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.9.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.8
      - regex==2025.11.3
      - requests==2.32.5
      - rouge-score==0.1.2
      - safetensors==0.6.2
      - sam2==1.1.0
      - sam3==0.1.0
      - scikit-image==0.25.2
      - scipy==1.16.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - tokenizers==0.21.4
      - torch==2.8.0+cu126
      - torchvision==0.23.0+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.4.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - webvtt-py==0.5.1
      - xxhash==3.5.0
      - yarl==1.20.1
      - yt-dlp==2025.11.12
      - yt-dlp-ejs==0.3.1
      - zstandard==0.25.0
prefix: /home/jmwood23/.conda/envs/qwen3
